### PR TITLE
Hotfix osx getopt

### LINKED ISSUE #31: bpc does not set the translated file to be executable
**Describe the bug**
After creating a new script with bpc running it results in "permission denied" until a chmod is run

**To Reproduce**
1. Create a new script with bpc
2. Attempt to run it

**Expected behavior**
The script runs

**Desktop (please complete the following information):**
 - OS: OSX
 - Version 14.5

### LINKED ISSUE #32: Bad error text when wrong getopt on OSX PATH
**Describe the bug**
Trying to run a simple script on OSX without gnu-getopt on the PATH will produce a hard to understand error (see Screenshots).

**To Reproduce**
1. Execute `echo "print()" | bpr -`
2. See error

**Expected behavior**
An understandable error that my PATH needs to be fixed to have brew's getopt before the system getopt.

**Screenshots**
/bin.  Will create or overwrite file co:.bpt
Failed to create translatedFilename correctly, script output was:
cat: co:.bpt: No such file or directory
Error (exit code 1) found on line 119.  Command was: cat "$translatedFilename"

**Desktop (please complete the following information):**
 - OS: OSX
 - Version 14.5

**Additional context**
OSX comes with the FreeBSD getopt that does not support long options

### PR DESCRIPTION
**Pull request by michael-amiethyst**
## Describe your changes
Added getopt check to bpc and bpr.  bpc also sets the created file to executable

## Issue ticket number and link
Closes #31 
Closes #32 

## Merge to Development - Checklist before requesting a review
- [x] I have performed a self-review of my code.  It runs with `mvn clean verify`
- [x] I have added thorough tests.

## Merge to Main - Checklist before requesting a review
- [ ] I have installed this version locally with `bin/deploy-head`
- [ ] I have tested on Debian with `docker build --no-cache -t "debian-bashpile" src/test/resources/docker/debian`
- [ ] I have regenerated the docutils documentation with `bin/generate-docs`

### CODE REVIEW

File: Formula/bashpile.rb [hunk 1]
```diff
@@ -3,7 +3,8 @@ class Bashpile < Formula
   homepage "https://github.com/michael-amiethyst/homebrew-bashpile"
   license "MIT"
   url "https://github.com/michael-amiethyst/homebrew-bashpile", using: :git, branch: "main", tag: "0.21.5"
-  head "https://github.com/michael-amiethyst/homebrew-bashpile", using: :git, branch: "development"
+  # TODO change back to "development"
```
Comment (michael-amiethyst) [inline Formula/bashpile.rb:6]: Change back to development

File: bin/bpc.bps [hunk 2]
```diff
@@ -43,3 +47,5 @@ if commandMode:
     #(java -jar "$jarPath" --outputFile="$translatedFilename" -c "$commandString")
 else:
     #(java -jar "$jarPath" --outputFile="$translatedFilename" "$@")
+
+chmod 755 $translatedFilename
```
Comment (michael-amiethyst) [inline bin/bpc.bps:51]: Add unit test to verify
